### PR TITLE
Generate client version 2.5.0

### PR DESCRIPTION
**Pull request by pierrejeambrun**
Don't merge it yet, as merging is considered as a 'release'.

[2.5.0rc1](https://github.com/apache/airflow-client-go/tree/2.5.0rc1) tag is pointing here, and should be enough for testing/voting.

### CODE REVIEW

**Comment by potiuk** [comment]
I have no choice but to trust it's been generated :D. We should improve it in the future so that we do not have to commit the committed code and that we do not have this sepearate repository IMHO. But this can be done later.

**Review by potiuk — APPROVED** [review]

**Comment by DrFaust92** [comment]
thanks @pierrejeambrun! this way i can test the terraform provider with [2.5.0rc1](https://github.com/apache/airflow-client-go/tree/2.5.0rc1)

**Comment by pierrejeambrun** [comment]
@potiuk @DrFaust92, @ephraimbuddy I noticed we had an issue. Generating the spec with the spec > 2.4.0 result in errors, because it cannot handle multiple tags for the same endpoint. We have on occurence of this in our spec:
https://github.com/apache/airflow/blob/main/airflow/api_connexion/openapi/v1.yaml#L912

Cf issue here:
https://github.com/OpenAPITools/openapi-generator/issues/741.

We end up having redefined struct and therefore will not work.

I generated the doc with the additional option specified `structPrefix=true`. Everything seems fine (internal name are just more verbose and without conflicts, api remains the same from a user point of view I believe)

I will make a PR on core to add this option to the generation process.

The other alternative is to remove/comment one of these tags to make it works. (doesn't seem maintainable)

**Comment by potiuk** [comment]
> I generated the client with the additional option specified structPrefix=true. Everything seems fine (internal name are just more verbose and without conflicts, api remains the same from a user point of view I believe)

Makes perfect sense.

**Comment by pierrejeambrun** [comment]
Regenerated the client with the latest release process to be sure I didn't miss the `security` or any other step.

**Review by potiuk — APPROVED** [review]

**Comment by pierrejeambrun** [comment]
I just added the `CHANGELOG.md` file to start tracking changes.

According to the project history, last release was https://github.com/apache/airflow-client-go/pull/23 on 9th May 2022, which is right after 2.3.0. Checking at the changes it seems to confirm that the last release was based on core 2.3.0. So the changelog for 2.5.0 is identical to 2.5.0 changelog for the python client. (going from 2.3.0 to 2.5.0)

**Comment by potiuk** [comment]
Also. I think it would be great to create actual GitHub releases from the tags (for both Python and Go client). -> it's super easy (create release from tag) and we might want to add it to our "Release process" to do so. I think Python 2.5.0 release was not created so we likely do not have it in the process.

**Review by potiuk — APPROVED** [review]

**Comment by pierrejeambrun** [comment]
Very good idea, there is a step like this for airflow but not for clients. I will update the release processes :+1:

**Pull request merged**
