### PR TITLE
Generated api client from the latest airflow main branch.

### PR DESCRIPTION
**Pull request by senthilkumarkj**
Generated using the following command,

bash ./gen/go.sh ../airflow/api_connexion/openapi/v1.yaml AIRFLOW_CLIENT_GO_REPO_PATH/airflow

This is mainly to pull in the fix for #20.

### CODE REVIEW

**Comment by senthilkumarkj** [comment]
Just got a chance to get back to this. There are a lot of changes than I originally intended to make. It appears the client might have been out of date. PTAL. @houqp 

One concerning change I see is that package version has been downgraded from `2.2.0` to `2.1.0`.

**Comment by senthilkumarkj** [comment]
Friendly ping on this PR. @houqp

**Comment by DrFaust92** [comment]
https://github.com/apache/airflow-client-go/pull/23 closes this as it has a bit newer spec

**Comment by houqp** [comment]
Thanks @DrFaust92! Apologize @senthilkumarkj for the late response.

**Pull request closed without merging**
