### PR TITLE
Update Go Client for Airflow 2.2.2

### PR DESCRIPTION
**Pull request by ajbosco**
Followed the [README](https://github.com/apache/airflow/tree/main/clients#usage) and generated Go client for Airflow 2.2.2

### CODE REVIEW

**Comment by ajbosco** [comment]
@houqp - Not sure if I did this correctly, so let me know if anything needs to be changed. This was generated off the `2.2.2` tag.

**Comment by houqp** [comment]
looks like the pre-commit that's supposed to append ASF license header didn't work. could you double check the run log to see if there was any runtime error?

**Comment by ajbosco** [comment]
> looks like the pre-commit that's supposed to append ASF license header didn't work. could you double check the run log to see if there was any runtime error?

@houqp - ah, I missed the `git add --update .` part. Fixed now.

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
Thanks @ajbosco !

**Pull request merged**
